### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by supertom44** [cancan101/xbmc-coursera#14] opened 2015-05-27 20:36 UTC
When trying to load the plugin I get the following error:

SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by cancan101** [comment] 2015-05-28 14:43
Is there any stack trace or additional information?

**Comment by supertom44** [comment] 2015-05-28 18:51
Apologises here is the full stack trace.

`19:50:24 T:4960  NOTICE: [plugin.video.coursera] Logging in
19:50:24 T:4960   ERROR: C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
19:50:26 T:4960   ERROR: Previous line repeats 1 times.
19:50:26 T:4960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
                                            Traceback (most recent call last):
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\xbmc-coursera-master\addon.py", line 291, in <module>
                                                plugin.run()
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\xbmc-coursera-master\addon.py", line 31, in index
                                                classes = loadClasses(username, password)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\xbmcmixin.py", line 81, in wrapper
                                                result = function(*args, **kwargs)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\xbmc-coursera-master\course_utils.py", line 53, in loadClasses
                                                classes = getClasses(cookies=cookies_raw)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\xbmc-coursera-master\course_utils.py", line 168, in getClasses
                                                data = get_page(COURSES_LIST_URL, json=True, **kwargs)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\xbmc-coursera-master\course_utils.py", line 71, in get_page
                                                res = requests.get(href, **kwargs)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 68, in get
                                                return request('get', url, **kwargs)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 50, in request
                                                response = session.request(method=method, url=url, **kwargs)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 464, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 576, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\Tom\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 431, in send
                                                raise SSLError(e, request=request)
                                            SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
                                            -->End of Python script error report<--
19:50:26 T:332   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.coursera/`

**Comment by dogrocker** [comment] 2015-06-14 00:42
got this error too.

**Comment by asfaltboy** [comment] 2015-06-25 20:54
This may be a duplicate of #13 (lack of SNI support), for which the fix is to upgrade Kodi's python version to py 2.7.9 or 3.4.X or have the system install a bunch of packages (pyOpenSSL pyasn1 ndg-httpsclient)... I've opened an issue on [kodi's trac](http://trac.kodi.tv/ticket/15883) in this regard

I hadn't had time to think of a cross platform solution, since those packages above require compiling per platform...

**Comment by cancan101** [comment] 2015-11-30 13:52
Closing as duplicate of #13. Reopen if you disagree.

**Closed by cancan101** 2015-11-30 13:52 UTC
